name:                tsil
version:             0.1.0.0
github:              "pgujjula/tsil"
license:             GPL-3
author:              "Preetham Gujjula"
maintainer:          "preethamgujjula@gmail.com"
copyright:           "2020 Preetham Gujjul"

extra-source-files:
- README.md

synopsis:            List utilities
category:            List

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pgujjula/tsil#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.List.Digit
#    - Data.List.Ordered.Predicate
#    - Data.List.Ordered.Transform
#    - Data.List.Predicate
    - Data.List.Transform
  dependencies:
    - text
    - text-show

executables:
  spec:
    source-dirs: test
    main: Spec.hs
    other-modules:
      - Data.List.DigitSpec
#      - Data.List.Ordered.PredicateSpec
#      - Data.List.Ordered.TransformSpec
#      - Data.List.PredicateSpec
      - Data.List.TransformSpec
    dependencies:
      - hspec
      - QuickCheck
      - tsil
      - random
